version: '3'
services:
  climamundi-api:
    build: 
      context: ./ClimaMundi
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
    env_file:
      - './ClimaMundi/.env'

  #Build react web app
  climamundi-web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production