version: '3'
services:
  climamundi-api:
    build: 
      context: ./ClimaMundi/ClimaMundi.Api/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
