version: '3'
services:
  climamundi-api:
    build: 
      context: ./ClimaMundi
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000

  #Build react web app
  climamundi-web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    volumes:
      - './web/src:/app/src'
      - './web/public:/app/public'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production #change this later
      - CHOKIDAR_USEPOLLING=true