version: '3'
services:
  climamundi-api:
    build: 
      context: ./ClimaMundi/ClimaMundi.Api/
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    env_file:
      - ClimaMundi/ClimaMundi.Api/.env
