# Configure ports etc.
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS builder
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Debug -o out

# Copy built code
FROM base AS runtime
WORKDIR /app
COPY --from=builder /app/ClimaMundi.Api/out ./
ENTRYPOINT ["dotnet", "ClimaMundi.Api.dll"]